### ISSUE TITLE
Abrir un archivo e iterar sobre sus lineas

### ISSUE THREAD

**Issue by mlafroce** [FdelMazo/7527-AlgoritmosIV#2]
Abrir un archivo, en lo posible utilizando argumentos de linea de comandos, y generar, en caso de *Success,* un *Traversable* de *Strings*.
Supongo que lo más fácil es empezar con un *Iterable* (p. ej, una lista)
En caso de que el archivo no exista (Failure), imprimir error y salir.

**Comment by FdelMazo** [comment]
Criterio de aceptacion: Imprimir lineas del csv por consola, y hacer archivo de prueba
