### ISSUE TITLE
Buscar alguna forma linda de llamar al constructor de DataSetRow

### ISSUE THREAD

**Issue by mlafroce** [FdelMazo/7527-AlgoritmosIV#6]
Ver si hay alguna forma linda de construir ese objeto con la lista de objects.

Aparentemente no tenemos unpack :(

https://stackoverflow.com/questions/15034565/is-there-a-scala-equivalent-of-the-python-list-unpack-a-k-a-operator

**Comment by mlafroce** [comment]
Este constructor debería devolver un Option o un Try, de forma que cuando hagamos un flatmap, los erroneos se filtren.

**Comment by FdelMazo** [comment]
Hacer que el constructor reciba una List[String] ? y por dentro haga todo el pasaje a los validators
